Fitosanidad/Controllers/AspersionPlanController.cs
using System;
using System.IO;
using System.Net;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Planner.Model;
using System.Data.SqlClient;
using System.Data;

namespace Fitosanidad.Controllers
{
    [Authorize]
    public class AspersionPlanController : BaseController
    {
        public class AspersionPlanConsolidated
        {
            public string AgrochemicalProductsID { get; set; }
            public string Lunes { get; set; }
            public string Martes { get; set; }
            public string Miercoles { get; set; }
            public string Jueves { get; set; }
            public string Luminosity { get; set; }
            public string Viernes { get; set; }
            public string Sabado { get; set; }
            public string Domingo { get; set; }
            public string total { get; set; }
            public int BussinesUnitId { get; set; }
            public int WeekID { get; set; }
        }

        SIEMBRAS_PLANNEREntities siembras_PLANNEREntities = null;
        public ActionResult Index()
        {
            siembras_PLANNEREntities = new SIEMBRAS_PLANNEREntities();
            var AspersionPlan = siembras_PLANNEREntities.fn_detalleAspersionPlan().ToList();
            ViewBag.datos = AspersionPlan;
            return View();
        }

        public ActionResult AspersionPlanAdd()
        {
            var ActualYear = DateTime.Today.Year;
            siembras_PLANNEREntities = new SIEMBRAS_PLANNEREntities();

            //Datos para dropDown de semanas
            var Week = siembras_PLANNEREntities.Semanas.OrderBy(a => a.ID).Where(x => x.Anio == ActualYear);
            SelectList listWeek = new SelectList((from s in Week
                                                  select new
                                                  {
                                                      ID = s.ID,
                                                      Nombre = s.Anio + "-" + s.Nombre
                                                  }),
                            "Id",
                            "Nombre",
                            null);
            ViewData["listWeek"] = listWeek;

            //Datos para dropDown de compañias
            var company = siembras_PLANNEREntities.Company.Where(x => x.FlagActivo == 1).Distinct().OrderBy(x => x.ID);
            SelectList CompanyList = new SelectList(company, "ID", "Nombre");
            ViewData["CompanyList"] = CompanyList;

            //Datos para dropDown de compañias
            var BussinesUnit = siembras_PLANNEREntities.fn_getAllFlowerGrowing().ToList();
            SelectList BussinesUnitList = new SelectList(BussinesUnit, "ID", "Name");
            ViewData["BussinesUnitList"] = BussinesUnitList;

            //Datos para dropDown de compañias
            var PlanProducts = siembras_PLANNEREntities.PlantProducts.Where(x => x.FlagActive == 1).Distinct().OrderBy(x => x.PlantProductName);
            SelectList PlanProductsList = new SelectList(PlanProducts, "PlantProductID", "PlantProductName");
            ViewData["PlanProductsList"] = PlanProductsList;

            //Datos para dropDown de compañias
            var aplyTypes = siembras_PLANNEREntities.Aspersion_ApplyTypes.Where(n => n.ActiveFlag == true).OrderBy(x => x.ApplyTypeID).ToList();
            SelectList aplyTypesList = new SelectList(aplyTypes, "ApplyTypeID", "Name");
            ViewData["aplyTypesList"] = aplyTypesList;

            //Datos para dropDown de formas
            var Forms = siembras_PLANNEREntities.Aspersion_Forms.Where(n => n.ActiveFlag == true).OrderBy(x => x.FormID).ToList();
            SelectList FormsList = new SelectList(Forms, "FormID", "Name");
            ViewData["FormsList"] = FormsList;

            //Datos para dropDown de productos agroquimicos
            var AgrochemicalProduct = siembras_PLANNEREntities.Aspersion_AgrochemicalProducts.Where(n => n.ActiveFlag == true).OrderBy(x => x.Name).ToList();
            SelectList AgrochemicalProductList = new SelectList(AgrochemicalProduct, "AgrochemicalProductsID", "Name");
            ViewData["AgrochemicalProductList"] = AgrochemicalProductList;

            //Datos para dropDown volumen tanque
            var tankVolume = siembras_PLANNEREntities.Aspersion_TankVolume.Where(n => n.ActiveFlag == true).OrderBy(x => x.Name).ToList();
            SelectList tankVolumeList = new SelectList(tankVolume, "TankVolumeID", "Name");
            ViewData["tankVolumeList"] = tankVolumeList;


            return View();
        }

        public ActionResult AspersionPlanAddHead(Aspersion_AspersionPlan datos)
        {

            datos.ActiveFlag = true;
            datos.DateInsert = DateTime.Today;
            siembras_PLANNEREntities = new SIEMBRAS_PLANNEREntities();

            Aspersion_AspersionPlan aspersion = siembras_PLANNEREntities.Aspersion_AspersionPlan.Where(x => x.WeekID == datos.WeekID && x.GreenHouseID == datos.GreenHouseID).FirstOrDefault();
            if (aspersion != null)
            {
                return Json("existe", JsonRequestBehavior.AllowGet);
            }

            siembras_PLANNEREntities.Aspersion_AspersionPlan.Add(datos);
            siembras_PLANNEREntities.SaveChanges();
            var AspersionPlanID = datos.AspersionPlanID;

            return Json(AspersionPlanID);
        }

        [HttpPost]
        public void CambiaEstadoHead(Aspersion_AspersionPlan datos)
        {
            try
            {
                siembras_PLANNEREntities = new SIEMBRAS_PLANNEREntities();
                Aspersion_AspersionPlan Update = siembras_PLANNEREntities.Aspersion_AspersionPlan.First(x => x.AspersionPlanID == datos.AspersionPlanID);
                Update.ActiveFlag = datos.ActiveFlag;
                siembras_PLANNEREntities.SaveChanges();
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public ActionResult AspersionPlanListDetail(Aspersion_AspersionPlanDetail datos)
        {
            siembras_PLANNEREntities = new SIEMBRAS_PLANNEREntities();
            var AspersionPlanList = siembras_PLANNEREntities.fn_DetalleAspersionPlanDetail(datos.AspersionPlanID).Where(x => x.Block > 0).OrderByDescending(a => a.AspersionPlanID).ToList();
            ViewBag.datos = AspersionPlanList;

            return PartialView("AspersionPlanList");
        }

        public JsonResult FiltroBloques()
        {
            siembras_PLANNEREntities = new SIEMBRAS_PLANNEREntities();
            var IdCompany = Request.QueryString["IdCompany"];
            if (IdCompany == "NaN")
                IdCompany = "0";
            var Id = Int32.Parse(IdCompany);

            //Datos para dropDown de compañias
            var aList = siembras_PLANNEREntities.fn_getGreenHousebyBusinessUnit(Id).OrderBy(a => a.Orden).ToList();
            SelectList lstGreenhouse = new SelectList(aList, "ID", "Codigo".Trim().ToUpper());
            return Json(lstGreenhouse);
        }

        public ActionResult AspersionPlanAddDetail(Aspersion_AspersionPlanDetail datos, string[] d)
        {
            siembras_PLANNEREntities = new SIEMBRAS_PLANNEREntities();
            var transac = siembras_PLANNEREntities.Database.BeginTransaction();

            //Consigue el consecutivo del orden de preparación
            var PreparationOrder = siembras_PLANNEREntities.Aspersion_AspersionPlanDetail.Where(
                x => x.AspersionPlanID == datos.AspersionPlanID &&
                x.Block == datos.Block &&
                x.DayNumber == datos.DayNumber &&
                x.AgrochemicalProductsID == datos.AgrochemicalProductsID &&
                x.ProductID == datos.ProductID).Select(x => x.PreparationOrder).DefaultIfEmpty(0).Max();
            var suma = 1;
            for (var i = 0; i < d.Length; i++)
            {
                datos.AgrochemicalProductsID = Convert.ToInt32(d[i]);
                //Verifica que no exista la llave bloque, dia, PPC y producto
                var verificaLlave = siembras_PLANNEREntities.Aspersion_AspersionPlanDetail.Where(
                        x => x.AspersionPlanID == datos.AspersionPlanID &&
                        x.Block == datos.Block &&
                        x.DayNumber == datos.DayNumber &&
                        x.AgrochemicalProductsID == datos.AgrochemicalProductsID &&
                        x.ProductID == datos.ProductID
                    ).FirstOrDefault();

                if (verificaLlave != null)
                {
                    var arr = new
                    {
                        Error = 1,
                        Mensaje = "Error en <b>PPC " + (i+1) + "</b>! Bloque / Día / Producto ya asignado, por favor verifique :" +
                        "<p>• Ya asignado anteriormente</p>" +
                        "<p>• Repetido en este formulario</p>",
                    };
                    transac.Rollback();
                    return Json(arr, JsonRequestBehavior.AllowGet);
                    
                }

                datos.PreparationOrder = (PreparationOrder + suma);

                var date = DateTime.Today;
                datos.DateInsert = date;
                siembras_PLANNEREntities.Aspersion_AspersionPlanDetail.Add(datos);
                siembras_PLANNEREntities.SaveChanges();

                suma++;
            }
            transac.Commit();
            return Json("Ok");
        }

        public ActionResult TraeID(Aspersion_AspersionPlan datos)
        {
            siembras_PLANNEREntities = new SIEMBRAS_PLANNEREntities();
            Aspersion_AspersionPlan aspersion = siembras_PLANNEREntities.Aspersion_AspersionPlan.Where(x => x.WeekID == datos.WeekID && x.GreenHouseID == datos.GreenHouseID).FirstOrDefault();

            DateTime Hoy = DateTime.Now;

            var datosDetalle = 0;
            if (aspersion != null)
            {

Fitosanidad/Views/AspersionPlan/AspersioPlanOutputTable.cshtml
@using Resources;
@using Planner.Model;


@model Planner.Model.Planner_Template

<script src="~/Scripts/Aspersion/AspersioPlanOutputTable.js"></script>


@{
    ViewBag.Title = "Plan de Aspersión";
    ViewBag.Subtitle = "Tabla de salida";
}

<div class="btn-group">
    <a id="btnHome" name="btnHome" class="btn btn-warning waves-effect waves-light" onclick="BackToList()" >
        <i class="fa fa-chevron-left"></i>
    </a>
    <button class="btn btn-danger waves-effect waves-light" id="exportPdf" onclick="exportPdf();" data-toggle="tooltip" data-placement="top" title="Generar plan de aspersión">
        <i class="fa fa-file-pdf-o"></i>
    </button>
    <button class="btn btn-success waves-effect waves-light" id="exportPdf" onclick="ImprimeEtiquetas(@ViewBag.Id)" data-toggle="tooltip" data-placement="top" title="Imprimir todas las etiquetas">
        <i class="fa fa fa-print"></i>
    </button>
    <button class="btn btn-primary" data-toggle="tooltip" data-placement="top" title="Generar plan de aspersión"><i class="fa fa-bar-chart" aria-hidden="true"></i></button>
</div>
<div class="Planner_Separator"></div>
<div class="Planner_Separator"></div>
<form id="AspersionPlanOutputTableForm">
    <div class="box box-success">
        <div class="box-body">
            <input type="hidden" value="@ViewBag.Id" id="Id"/>
            <div class="col-md-3">
                <label class="label_title">No. Semana: </label><br />
                @Html.DropDownList("WeekID", ViewData["listWeek"] as SelectList, "Todas", new { @class = "form-control", @style = "width:100%", @id = "WeekID" })
            </div>

            <div class="col-md-3">
                <label class="label_title">Día: </label><br />
                <select id="NumberDay" class="form-control">
                    <option value="">Todos</option>
                    <option value="1">LUNES</option>
                    <option value="2">MARTES</option>
                    <option value="3">MIERCOLES</option>
                    <option value="4">JUEVES</option>
                    <option value="5">VIERNES</option>
                    <option value="6">SABADO</option>
                    <option value="7">DOMINGO</option>
                </select>
            </div>

            <div class="col-sm-3">
                <label class="label_title">Supervisor: </label><br />
                @Html.DropDownList("AspersionEmployeesID", ViewData["AspersionEmployesList"] as SelectList, "Todos", new { @class = "form-control", @style = "width:100%", @id = "AspersionEmployeesID" })
            </div>
            <input type="hidden" id="Supervisor"/>
            <div class="col-sm-3">
                <br />
                <button type="button" class="btn btn-primary" id="OutputTableFilter"><i class="fa fa-filter"></i></button>
            </div>
        </div>
    </div>
</form>
<div class="box box-success">
    <div class="box-body">
        @foreach (var ds in ViewBag.AspersionPlan)
        {
            <div class="col-lg-12 text-center">
                <h4 id="tituloOutput"><b>Plan de aspersión semana @ds.WeekID Finca: @ds.GreenHouseID<br />   <span id="supervisores"></span></b></h4>
            </div>
        }
        <div class="Planner_Separator"></div>
        <div style="overflow:scroll;height: 500px;">
            <table id="table_AspersionPlanOutput" class="table table-bordered table-striped table-condensed table-hover" style="font-size:10px">
                <thead>
                    <tr>
                        <th></th>
                        <th>Dia</th>
                        <th>Bl</th>
                        <th>Camas</th>
                        <th>Orden</th>
                        <th>PPC</th>
                        <th>I.Act</th>
                        <th>Dosis</th>
                        <th>CTox</th>
                        <th>BlBio</th>
                        <th>Unid</th>
                        <th>Rein</th>
                        <th>LxCama</th>
                        <th>Lanza</th>
                        <th>TxLado</th>
                        <th>Obs</th>
                        <th>TotGr</th>
                        <th>TVol</th>
                        <th>AguaTan</th>
                        <th>AguaSal</th>
                        <th>#Tan</th>
                        <th>PPCXTGr</th>
                        <th>PPCXTSal</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var d in ViewBag.PlanProducts)
                    {
                    <tr>
                        <td><button class="btn btn-xs" onclick="location='/AspersionPlan/imprimeEtiquetas/@ViewBag.Id?IdDetail=@d.AspersionPlanDetailID'"><i class="fa fa-print text-navy"></i></button></td>
                        <td>@d.DayNumber</td>
                        <td>@d.Block</td>
                        <td>@d.BedNumber</td>
                        <td>@d.PreparationOrder</td>
                        <td>@d.AgrochemicalProductsID</td>
                        <td>@d.ActiveIngredient</td>
                        <td>@Math.Round(d.dose,1)</td>
                        <td>@d.ToxicologicalCategoryID</td>
                        <td>@d.PlagasID</td>
                        @*<td>@d.MeasurementUnitsID</td>*@
                        <td>GR</td>
                        <td>@d.ReentryHourID</td>
                        <td>@Math.Round(d.LiterPerBed)</td>
                        <td>@d.ReferenceSpear</td>
                        <td>@(Math.Ceiling(d.TimePerSide))</td>
                        <td>@d.Observation</td>
                        @if (d.Sald % d.TankVolume == 0)
                        {
                            d.Sald = 0;
                        }
                        else
                        {
                            d.Sald = Math.Round(Math.Abs(d.Sald), 1);
                        }
                        @{
                            decimal totGr = 0;
                            decimal GRxTr = 0;
                        }
                        @if (d.MeasurementUnitsID == "CC")
                        {
                            var total = (d.dose * d.Density) * d.BedNumber * d.LiterPerBed;
                            <td>@(Math.Round(total, 1))</td>
                            totGr = Math.Round((d.TankVolume * d.dose * d.Density), 1);
                            GRxTr = Math.Round((d.Sald * d.dose * d.Density), 1);
                        }
                        else
                        {
                            var total = d.dose * d.BedNumber * d.LiterPerBed;
                            <td>@(Math.Round(total, 1))</td>
                            totGr = Math.Round((d.TankVolume * d.dose), 1);
                            GRxTr = Math.Round((d.Sald * d.dose), 1);

                        }
                        <td>@(Math.Round(d.TotalVolume, 1))</td>
                        <td>@Math.Round(d.TankVolume, 1)</td>
                        @{var NumeTarros = (Math.Ceiling((d.BedNumber * d.LiterPerBed) / d.TankVolume));}
                        <td>@(d.Sald)</td>
                        <td>@NumeTarros</td>
                        <td>@totGr</td>
                        <td>@GRxTr</td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<script src="https://unpkg.com/jspdf@1.5.3/dist/jspdf.min.js"></script>
<script src="https://unpkg.com/jspdf-autotable@3.0.13/dist/jspdf.plugin.autotable.js"></script>

Fitosanidad/Views/AspersionPlan/AspersionPlanAdd.cshtml
@using Resources;
@using Planner.Model;


@model Planner.Model.Planner_Template

@{
    ViewBag.Title = "Plan de Aspersión";
    ViewBag.Subtitle = "Agregar Nuevo registro";
}

<script src="~/Scripts/Aspersion/AspersionPlanAdd.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        var bootstrapTooltip = $.fn.tooltip.noConflict();
        $.fn.bstooltip = bootstrapTooltip;
        $(this).find("button").each(function () {
            $(this).bstooltip();
        })
    })
</script>

<form class="" id="form_AspersionPlan">
    @Html.Hidden("AspersionPlanID")
    <div class="btn-group">
        <a id="btnHome" name="btnHome" class="btn btn-warning waves-effect waves-light" onclick="BackToList()">
            <i class="fa fa-chevron-left"></i>
        </a>
    </div>

    <div class="clearfix"></div>
    <br />
    <div class="box box-success">
        <div class="box-body">
            <div class="col-sm-2">
                <label for="Name">Semana: </label>
                @Html.DropDownList("listWeek", ViewData["listWeek"] as SelectList, "Seleccione", new { @class = "form-control", @style = "width:100%", @id = "WeekID" })
            </div>

            <div class="col-sm-4 form-inline">
                <label class="label_title">Finca: </label><br />
                @Html.DropDownList("BussinesUnitList", ViewData["BussinesUnitList"] as SelectList, "Seleccione", new { @class = "form-control", @style = "width:100%", @id = "GreenHouseID" })
                <button class="btn btn-success btn-sm" id="bt_AspersionPlanAdd" data-toggle="tooltip" data-placement="top" title="Crear Plan"><i class="fa fa-plus"></i></button>
            </div>
        </div>
    </div>
</form>

<form class="" id="form_AspersionPlanDetail" style="display: none;">
    <div class="btn-group">
        <button class="btn btn-success" id="bt_AspersionPlanDetailAdd" data-toggle="tooltip" data-placement="top" title="Adicionar Producto" type="submit"><i class="fa fa-plus"></i></button>
    </div>
    <div class="clearfix"></div>
    <br />
    <div class="box box-success">
        <div class="box-body">
            <div class="col-md-4 form-inline">
                <label class="label_title">Producto: </label><br />
                @Html.DropDownList("PlanProductsList", ViewData["PlanProductsList"] as SelectList, "", new { @class = "form-control", @style = "width:100%", @id = "ProductID" })
            </div>

            <div class="col-md-2 form-inline">
                <label class="label_title">Bloque: </label><br />
                <select id="Block" name="Block" class="form-control" required>
                    <option>---</option>
                </select>
            </div>

            <div class="col-md-2 form-inline">
                <label class="label_title">Día: </label><br />
                <select id="DayNumber" name="DayNumber" class="form-control" required>
                    <option value="1">Lunes</option>
                    <option value="2">Martes</option>
                    <option value="3">Miércoles</option>
                    <option value="4">Jueves</option>
                    <option value="5">Viernes</option>
                    <option value="6">Sábado</option>
                    <option value="7">Domingo</option>
                </select>
            </div>

            <div class="col-md-4 form-inline">
                <label class="label_title">Aplicación: </label><br />
                @Html.DropDownList("aplyTypesList", ViewData["aplyTypesList"] as SelectList, new { @class = "form-control", @style = "width:100%", @id = "ApplyTypesID" })
            </div>

            <div class="clearfix"></div>

            <div class="col-md-4 form-inline">
                <label class="label_title">Forma: </label><br />
                @*@Html.DropDownList("FormsList", ViewData["FormsList"] as SelectList, new { @class = "form-control", @style = "width:100%", @id = "FormID" })*@
                <input type="text" class="form-control" id="FormsList" required />
            </div>

            <div class="col-md-2 form-inline">
                <label class="label_title">Orden de preparación: </label><br />
                <input type="text" class="form-control" id="PreparationOrder" required />
            </div>

            <div class="col-md-2 form-inline">
                <label class="label_title">Camas a programar: </label><br />
                <input type="text" class="form-control" id="BedNumber" required />
            </div>

            <div class="col-md-4 form-inline">
                <label class="label_title">PPC: </label><br />
                @Html.DropDownList("AgrochemicalProductList", ViewData["AgrochemicalProductList"] as SelectList, new { @class = "form-control", @style = "width:100%", @id = "AgrochemicalProductsID" })
            </div>

            <div class="clearfix"></div>

            <div class="col-md-2 form-inline">
                <label class="label_title">Litros por cama: </label>
                <input type="text" class="form-control" id="LiterPerBed" required />
            </div>

            <div class="col-md-2 form-inline">
                <label class="label_title">No. de asperjadores: </label>
                <input type="text" class="form-control" id="AsperjadorNumber" required />
            </div>

            <div class="col-md-2 form-inline">
                <label class="label_title">Volumen tanque: </label>
                <input type="text" class="form-control" id="TankVolume" required />
            </div>

            <div class="col-md-2 form-inline">
                <label class="label_title">Capacidad tarro: </label>
                @*<input type="text" class="form-control" id="CapacityJar" value="1000" readonly />*@
                @Html.TextBox("CapacityJar", "1000", new { @class = "form-control", @readonly = "readonly" })
            </div>

            <div class="col-md-4 form-inline">
                <label class="label_title">Observaciones: </label><br />
                @Html.TextArea("Observation", new { @class = "form-control", @id = "Observation" })
            </div>
            <!--Campos que se calculan automaticos-->
            <hr />

            <hr />
        </div>
        <div class="col-md-12 text-center text-green"><h4><b>Detalle</b></h4></div>
        <hr />
        <div class="col-md-12 form-group" id="AspersionPlanListDetail" style="width:100%; overflow:scroll;">
            <!--Tabla detalle-->
        </div>
    </div>
</form>

<div class="modal fade" id="modalMensajes" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="modalMensajesTitulo"></h4>
            </div>
            <div class="modal-body text-center" id="modalMensajesCuerpo">
            </div>
            <div class="modal-footer">
                <div id="modalMensajesFooter"></div>
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

Fitosanidad/Views/AspersionPlan/AspersionPlanList.cshtml
<table id="TableAspersionPlan" class="frozen_alert table table-bordered table-striped table-condensed table-hover" style="width : auto;">
    <thead>
        <tr>
            <th>ID</th>
            <th>Producto</th>
            <th>Bloque</th>
            <th>Día</th>
            <th>Aplicación</th>
            <th>Forma</th>
            <th>Orden</th>
            <th>Producto Agro.</th>
            <th>No. Camas</th>
            <th>Litros*Cama</th>
            <th>Lanza</th>
            <th>No. Asper.</th>
            <th>Observaciones</th>
            <th>Vol. Tanque</th>
            <th>Capa.Tarro</th>
            <th>Estado</th>
            <th>Edicion</th>
        </tr>
    </thead>
    <tbody>
        @{ var i = 0;}
        @{ var af = 0;}
        @foreach (var template in ViewBag.datos)
        {
            <tr>
                <td>@template.AspersionPlanDetailID</td>
                <td>@template.ProductID</td>
                <td>@template.Block</td>
                <td>@template.DayNumber</td>
                <td>@template.ApplyTypesID</td>
                <td>@template.FormID</td>
                <td>@template.PreparationOrder</td>
                <td>@template.AgrochemicalProductsID</td>
                <td>@template.BedNumber</td>
                <td>@Math.Round(template.LiterPerBed, 1)</td>
                <td>@template.ReferenceSpear</td>
                <td>@template.AsperjadorNumber</td>
                <td>@template.Observation</td>
                <td>@Math.Round(template.TankVolume, 1)</td>
                <td>@Math.Round(template.CapacityJar, 1)</td>

                @if (template.ActiveFlag == true)

                {
                    af = 1;
                    <td class="text-success text-bold">Activo</td>
                }
                else
                {
                    af = 0;
                    <td class="text-danger text-bold">Inactivo</td>
                }

                <td class="actions">
                    <a href=@Url.Action("AspersionPlanEdit", "AspersionPlan", new { id = @template.AgrochemicalProductsID }) class="on-default edit-row" title="Editar"><i class="fa fa-pencil fa-1x"></i></a> |
                    <a href="javascript:void(0);" class="on-default remove-row" title="Activar/Desactivar" onclick="CambiaEstado(@af, @template.AspersionPlanID);"><i class="fa fa-toggle-on fa-1x"></i></a>
                </td>
            </tr>
            i++;
        }
    </tbody>
</table>
<script type="text/javascript">
    var table = $("#TableAspersionPlan").dataTable();
</script>

Fitosanidad/Views/AspersionPlan/Index.cshtml
@using Resources;
@using Planner.Model;


@model Planner.Model.Planner_Template
<script src="~/Scripts/Aspersion/AspersionPlan.js"></script>
@{
    ViewBag.Title = "Plan de Aspersión";
    ViewBag.Subtitle = "Listado de planes por semana y finca";
}
<div class="btn-group">
    <a id="btnCreate" name="btnCreate" class="btn btn-success waves-effect waves-light">
        <i class="fa fa-plus"></i>
    </a>
    @*<button id="AspersioPlanOutputTable" name="AspersioPlanOutputTable" title="Generar tabla plan de aspersión" class="btn btn-success waves-effect waves-light">
        <i class="fa fa-list"></i>
    </button>*@
</div>
<div class="Planner_Separator"></div>
<div class="box box-success">
    <div class="box-body">

        <div class="col-md-12 form-group">
            <table id="table_AspersionPlan" class="frozen_alert table table-bordered table-striped table-condensed table-hover">
                <thead>
                    <tr>
                        <th>Id.</th>
                        <th>Semana</th>
                        <th>Finca</th>
                        <th>Estado</th>
                        <th>Fecha</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var ds in ViewBag.datos)
                    {
                        <tr>
                            <td>@ds.AspersionPlanID</td>
                            <td>@ds.WeekID</td>
                            <td>@ds.GreenHouseID</td>
                            @{ var af = 0;}
                            @if (ds.ActiveFlag == true)
                            {
                                af = 1;
                                <td class="text-success text-bold">Activo</td>
                            }
                            else
                            {
                                af = 0;
                                <td class="text-danger text-bold">Inactivo</td>
                            }
                            <td>@ds.DateInsert</td>
                            <td class="actions">
                                <button class="btn btn-xs" onclick="location='@Url.Action("AspersionPlanEdit", "AspersionPlan", new { id = ds.AspersionPlanID })'" data-toggle="tooltip" data-placement="top" title="Editar Plan"><i class="fa fa-pencil text-primary"></i></button>

                                @if (ds.ActiveFlag == true)
                                {
                                    <button class="btn btn-xs" onclick="CambiaEstado(@af, @ds.AspersionPlanID);" data-toggle="tooltip" data-placement="top" title="Desactivar Plan"><i class="fa fa-toggle-on text-success"></i></button>
                                }
                                else
                                {
                                    <button class="btn btn-xs" onclick="CambiaEstado(@af, @ds.AspersionPlanID);" data-toggle="tooltip" data-placement="top" title="Activar Plan"><i class="fa fa-toggle-off text-danger"></i></button>
                                }

                                <button class="btn btn-xs" onclick="location='@Url.Action("AspersioPlanOutputTable", "AspersionPlan", new { id = ds.AspersionPlanID })'" data-toggle="tooltip" data-placement="top" title="Visualizar plan de aspersión"><i class="fa fa-print text-navy"></i></button>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>
</div>
<script type="text/javascript">$("#table_AspersionPlan").DataTable();</script>