Fitosanidad/Controllers/IOT_SensorListController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services;
using System.Web.UI.WebControls;

using Planner.Model;
using System.Data;
using System.Data.SqlClient;
using Newtonsoft.Json;
using System.Threading.Tasks;
using System.Net;
using System.Net.Http;
using System.Xml.Linq;
using System.Globalization;

namespace Fitosanidad.Controllers
{
    [Authorize]
    public class IOT_SensorListController : BaseController
    {
        SIEMBRAS_PLANNEREntities siembras_PLANNEREntities = null;
        SelectList businessUnitList = null;
        SelectList greenhouseList = null;
        SelectList sensorInstallList = null;

        public class UploadSensor
        {
            public string DataMessageGUID { get; set; }
            public string SensorID { get; set; }
            public string Date { get; set; }
            public string Humidity { get; set; }
            public string Temperature { get; set; }
            public string Luminosity { get; set; }
        }

        public class SensorData
        {
            public string DeviceId { get; set; }
            public string Value { get; set; }
            public string Data { get; set; }
            public string BusinessUnitId { get; set; }
            public string GreenHouseID { get; set; }
            public string Time { get; set; }
            public string Sensor { get; set; }
        }

        public ActionResult Index()
        {
            siembras_PLANNEREntities = new SIEMBRAS_PLANNEREntities();
            ViewBag.SensorList = siembras_PLANNEREntities.fn_getIOT_SensorList().OrderBy(x => x.BusinessUnitName).ThenBy(x => x.Codigo);

            return View();
        }

        public ActionResult Create()
        {
            int BusinessUnitId = 0;

            siembras_PLANNEREntities = new SIEMBRAS_PLANNEREntities();
            var businessUnitList_Lst = siembras_PLANNEREntities.fn_getAllFlowerGrowing().Where(n => n.ID != 0).OrderBy(x => x.Name).ToList();
            businessUnitList = new SelectList(businessUnitList_Lst, "ID", "Name".Trim().ToUpper());
            ViewData["businessUnitList"] = businessUnitList;

            BusinessUnitId = businessUnitList_Lst.FirstOrDefault().ID;

            var greenhouseList_Lst = siembras_PLANNEREntities.fn_getGreenHouseSensorInstall(BusinessUnitId).OrderBy(a => a.Codigo);
            greenhouseList = new SelectList((from s in greenhouseList_Lst.ToList()
                                             select new
                                             {
                                                 ID = s.ID,
                                                 Codigo = s.Codigo + " - Cód. " + s.ID
                                             }),
                            "ID",
                            "Codigo",
                            BusinessUnitId);
            ViewData["greenhouseList"] = greenhouseList;
            return View();
        }

        public ActionResult Edit(int IOT_SensorListID)
        {
            siembras_PLANNEREntities = new SIEMBRAS_PLANNEREntities();

            IOT_SensorList _IOT_SensorList = siembras_PLANNEREntities.IOT_SensorList.Where(x => x.IOT_SensorListID == IOT_SensorListID).FirstOrDefault();
            if (_IOT_SensorList == null)
            {
                return RedirectToAction("Index");
            }

            var businessUnitList_Lst = siembras_PLANNEREntities.fn_getAllFlowerGrowing().Where(n => n.ID != 0).OrderBy(x => x.Name).ToList();
            businessUnitList = new SelectList(businessUnitList_Lst, "ID", "Name".Trim().ToUpper(), _IOT_SensorList.BusinessUnitID);
            ViewData["businessUnitList"] = businessUnitList;

            var greenhouseList_Lst = siembras_PLANNEREntities.fn_getGreenHouseSensorInstall(_IOT_SensorList.BusinessUnitID).OrderBy(a => a.Codigo);
            greenhouseList = new SelectList((from s in greenhouseList_Lst.ToList()
                                             select new
                                             {
                                                 ID = s.ID,
                                                 Codigo = s.Codigo + " - Cód. " + s.ID
                                             }),
                            "ID",
                            "Codigo",
                            _IOT_SensorList.GreenHouseID);
            ViewData["greenhouseList"] = greenhouseList;
            return View(_IOT_SensorList);
        }

        public ActionResult Delete(int IOT_SensorListID)
        {
            siembras_PLANNEREntities = new SIEMBRAS_PLANNEREntities();

            IOT_SensorList _IOT_SensorList = siembras_PLANNEREntities.IOT_SensorList.Where(x => x.IOT_SensorListID == IOT_SensorListID).FirstOrDefault();
            if (_IOT_SensorList == null)
            {
                return RedirectToAction("Index");
            }

            var businessUnitList_Lst = siembras_PLANNEREntities.fn_getAllFlowerGrowing().Where(n => n.ID != 0).OrderBy(x => x.Name).ToList();
            businessUnitList = new SelectList(businessUnitList_Lst, "ID", "Name".Trim().ToUpper(), _IOT_SensorList.BusinessUnitID);
            ViewData["businessUnitList"] = businessUnitList;

            var greenhouseList_Lst = siembras_PLANNEREntities.fn_getGreenHouseSensorInstall(_IOT_SensorList.BusinessUnitID).OrderBy(a => a.Codigo);
            greenhouseList = new SelectList((from s in greenhouseList_Lst.ToList()
                                             select new
                                             {
                                                 ID = s.ID,
                                                 Codigo = s.Codigo + " - Cód. " + s.ID
                                             }),
                            "ID",
                            "Codigo",
                            _IOT_SensorList.GreenHouseID);
            ViewData["greenhouseList"] = greenhouseList;
            return View(_IOT_SensorList);
        }

        public ActionResult Upload(int IOT_SensorListID)
        {
            siembras_PLANNEREntities = new SIEMBRAS_PLANNEREntities();

            IOT_SensorList _IOT_SensorList = siembras_PLANNEREntities.IOT_SensorList.Where(x => x.IOT_SensorListID == IOT_SensorListID).FirstOrDefault();
            if (_IOT_SensorList == null)
            {
                return RedirectToAction("Index");
            }

            var businessUnitList_Lst = siembras_PLANNEREntities.fn_getAllFlowerGrowing().Where(n => n.ID != 0).OrderBy(x => x.Name).ToList();
            businessUnitList = new SelectList(businessUnitList_Lst, "ID", "Name".Trim().ToUpper(), _IOT_SensorList.BusinessUnitID);
            ViewData["businessUnitList"] = businessUnitList;

            var greenhouseList_Lst = siembras_PLANNEREntities.fn_getGreenHouseSensorInstall(_IOT_SensorList.BusinessUnitID).OrderBy(a => a.Codigo);
            greenhouseList = new SelectList((from s in greenhouseList_Lst.ToList()
                                             select new
                                             {
                                                 ID = s.ID,
                                                 Codigo = s.Codigo + " - Cód. " + s.ID,
                                             }),
                            "ID",
                            "Codigo",
                            _IOT_SensorList.GreenHouseID);
            ViewData["greenhouseList"] = greenhouseList;
            return View(_IOT_SensorList);
        }

        [HttpPost]
        public ActionResult UploadFromFile()
        {
            string _DataMessageGUID = string.Empty;
            string _SensorID = string.Empty;
            string _Date = string.Empty;
            string _DataRaw = string.Empty;
            string _Humidity = string.Empty;
            string _Temperature = string.Empty;
            string _Luminosity = string.Empty;

            try
            {
                if (System.Web.HttpContext.Current.Request.Files.AllKeys.Any())
                {
                    var pic = System.Web.HttpContext.Current.Request.Files["HelpSectionImages"];
                    HttpPostedFileBase filebase = new HttpPostedFileWrapper(pic);
                    var fileName = Path.GetFileName(filebase.FileName);
                    var path = Path.Combine(Server.MapPath("~/Uploads/"), fileName);
                    filebase.SaveAs(path);

                    DataTable dtUpload = HelperController.Csv2DataTable(path);
                    List<UploadSensor> lstUpload = new List<UploadSensor>();
                    for (int i = 0; i < dtUpload.Rows.Count; i++)
                    {
                        UploadSensor _UploadSensor = new UploadSensor();

                        _DataMessageGUID = dtUpload.Rows[i][0].ToString().Trim();
                        _SensorID = dtUpload.Rows[i][1].ToString().Trim();
                        _Date = dtUpload.Rows[i][2].ToString().Trim();
                        _DataRaw = dtUpload.Rows[i][3].ToString().Trim();
                        _DataRaw = _DataRaw.Substring(1, _DataRaw.Length - 2);

                        _Humidity = _DataRaw.Split(',')[0].Trim();
                        _Temperature = _DataRaw.Split(',')[1].Trim();
                        _Luminosity = string.Empty;

                        _UploadSensor.DataMessageGUID = _DataMessageGUID.Substring(1, _DataMessageGUID.Length - 2);
                        _UploadSensor.SensorID = _SensorID.Substring(1, _SensorID.Length - 2);
                        _UploadSensor.Date = Convert.ToDateTime(_Date.Replace("\"", ""), new CultureInfo("en-US")).AddHours(-5).ToString();
                        _UploadSensor.Humidity = _Humidity;
                        _UploadSensor.Temperature = _Temperature;
                        _UploadSensor.Luminosity = _Luminosity;
                        lstUpload.Add(_UploadSensor);
                    }

Fitosanidad/Views/IOT_SensorList/Create.cshtml
@using Resources;
@using Planner.Model;

@{
    ViewBag.Title = Resources.Sensores + " - " + Resources.Adicionar;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/IOT_SensorList/Create.js"></script>

<div class="btn-group">
    <button id="btnHome" name="btnHome" class="btn btn-warning waves-effect waves-light" onclick='BackToList()'>
        <i class="fa fa-chevron-left"></i>
    </button>
    <button id="btnSave" name="btnSave" class="btn btn-success waves-effect waves-light" onclick="CallSubmit()">
        <i class="fa fa-save"></i>
    </button>
</div>
<div class="Planner_Separator">
</div>

@Html.Hidden("IOT_SensorListID")

<div class="box box-success">
    <div class="box-body">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="col-xs-12 col-sm-4 col-md-4">
                <label for="businessUnitList">Unidad de Negocio:</label>
                @Html.DropDownList("ddlBusinessUnit", ViewData["businessUnitList"] as SelectList, new { @class = "form-control" })
            </div>
            <div class="col-xs-12 col-sm-4 col-md-4">
                <label for="greenhouseList">@Resources.Bloque</label>
                @Html.DropDownList("ddlGreenhouse", ViewData["greenhouseList"] as SelectList, new { @class = "form-control", onchange = "greenhouseListOnChange()" })
            </div>
            <div class="col-xs-12 col-sm-4 col-md-4">
                <label for="Description">@Resources.Ubicacion</label>
                @Html.TextBox("AddName", null, new { @class = "form-control", @id = "AddName" })
            </div>

            <div class="col-xs-12 col-sm-4 col-md-4">
                <label for="lstPlanner_TemplateType">@Resources.ServicioWeb</label>
                <div class="controls">
                    @Html.TextBox("AddService", null, new { @class = "form-control", @id = "AddService" })
                </div>
            </div>
            <div class="col-xs-12 col-sm-4 col-md-4">
                <label for="lstPlanner_TemplateType">@Resources.IdSensor</label>
                <div class="controls">
                    @Html.TextBox("AddExternalID", null, new { @class = "form-control", @id = "AddExternalID" })
                </div>
            </div>

            <div class="col-xs-12 col-sm-1 col-md-1">
                <label for="ActiveFlag">@Resources.Activo</label>
                @Html.CheckBox("AddFlagActive", false, new { @class = "checkbox" })
            </div>
        </div>
    </div>
</div>

Fitosanidad/Views/IOT_SensorList/Delete.cshtml
@using Resources;
@using Planner.Model;

@model Planner.Model.IOT_SensorList


@{
    ViewBag.Title = Resources.Sensores + " - " + Resources.Borrar;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/IOT_SensorList/Delete.js"></script>

<div class="btn-group">
    <button id="btnHome" name="btnHome" class="btn btn-warning waves-effect waves-light" data-toggle="tooltip" data-placement="top" title="@Resources.VolverALaLista" onclick='BackToList()'>
        <i class="fa fa-chevron-left"></i>
    </button>
    <button id="btnDelete" name="btnDelete" class="btn btn-danger waves-effect waves-light" data-toggle="tooltip" data-placement="top" title="@Resources.Borrar" onclick="CallSubmit()">
        <i class="fa fa-trash-o"></i>
    </button>
</div>
<div class="Planner_Separator">
</div>

@Html.Hidden("IOT_SensorListID")

<div class="box box-success">
    <div class="box-body">
        <div class="col-xs-12 col-sm-12 col-md-12">
            @using (Html.BeginForm("Edit", "IOT_SensorList", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form", id = "Edit" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                @Html.HiddenFor(model => model.IOT_SensorListID)

                <div class="col-xs-12 col-sm-4 col-md-4">
                    <label for="businessUnitList">Unidad de Negocio:</label>
                    @Html.DropDownList("businessUnitList", ViewData["businessUnitList"] as SelectList, new { @class = "form-control", @disabled = "disabled" })
                </div>
                <div class="col-xs-12 col-sm-4 col-md-4">
                    <label for="greenhouseList">@Resources.Bloque</label>
                    @Html.DropDownList("greenhouseList", ViewData["greenhouseList"] as SelectList, new { @class = "form-control", @disabled = "disabled" })
                </div>
                <div class="col-xs-12 col-sm-4 col-md-4">
                    <label for="Description">@Resources.Ubicacion</label>
                    @Html.TextBoxFor(model => model.Name, null, new { @class = "form-control", @placeholder = Resources.Ubicacion, @readonly = "readonly" })
                </div>

                <div class="col-xs-12 col-sm-4 col-md-4">
                    <label for="lstPlanner_TemplateType">@Resources.ServicioWeb</label>
                    <div class="controls">
                        @Html.TextBoxFor(model => model.Service, null, new { @class = "form-control", @placeholder = Resources.ServicioWeb, @readonly = "readonly" })
                    </div>
                </div>
                <div class="col-xs-12 col-sm-4 col-md-4">
                    <label for="lstPlanner_TemplateType">@Resources.IdSensor</label>
                    <div class="controls">
                        @Html.TextBoxFor(model => model.ExternalID, null, new { @class = "form-control", @placeholder = Resources.IdSensor, @readonly = "readonly" })
                    </div>
                </div>

                <div class="col-xs-12 col-sm-1 col-md-1">
                    <label for="ActiveFlag">@Resources.Activo</label>
                    @Html.CheckBoxFor(model => model.FlagActive, new { @class = "checkbox", @disabled = "disabled" })
                </div>
            }
        </div>
    </div>
</div>

Fitosanidad/Views/IOT_SensorList/DeleteDateRange.cshtml
@using Resources;
@using Planner.Model;

@model Planner.Model.IOT_SensorList

@{
    ViewBag.Title = Resources.Sensores + " - " + Resources.BorrarInformacionEnUnRangoDeFechas;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/IOT_SensorList/DeleteDateRange.js"></script>

<div class="btn-group">
    <button id="btnHome" name="btnHome" class="btn btn-warning waves-effect waves-light" data-toggle="tooltip" data-placement="top" title="@Resources.VolverALaLista" onclick='BackToList()'>
        <i class="fa fa-chevron-left"></i>
    </button>
</div>
<div class="Planner_Separator">
</div>

@Html.HiddenFor(m => m.BusinessUnitID)
@Html.HiddenFor(m => m.GreenHouseID)
@Html.HiddenFor(m => m.ExternalID)

<div class="box box-success">
    <div class="box-body">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="col-xs-12 col-sm-2 col-md-2">
                <label for="startDate">@Resources.FechaInicial</label>
                @Html.TextBox("startDate", null, new { @class = "form-control", @id = "startDate" })
            </div>
            <div class="col-xs-12 col-sm-2 col-md-2">
                <label for="endDate">@Resources.FechaFinal</label>
                @Html.TextBox("endDate", null, new { @class = "form-control", @id = "endDate" })
            </div>
            <div class="col-xs-12 col-sm-2 col-md-2">
                <label for="Description">@Resources.Acciones</label>
                <br />
                <div class="btn-group">
                    <button id="btnSearch" name="btnSearch" class="btn btn-warning waves-effect waves-light" data-toggle="tooltip" data-placement="top" title="@Resources.Buscar" onclick='Search()'>
                        <i class="fa fa-search"></i>
                    </button>
                    <button id="btnDelete" name="btnDelete" class="btn btn-danger waves-effect waves-light" data-toggle="tooltip" data-placement="top" title="@Resources.Borrar" onclick='Delete()'>
                        <i class="fa fa-trash"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="box box-success">
    <div class="box-body">
        <div class="col-xs-12 col-sm-10 col-md-10">
            <div id="SensorDataDataTable">
                <div id="SensorDataListDataTable" class="form-group row">
                    <div id="resultsSensorDataList">
                        <table id="tableSensorDataList" class="table table-bordered table-striped table-condensed table-hover" style="width:100%;">
                            <thead>
                                <tr>
                                    <th>@Resources.Fecha</th>
                                    <th>@Resources.Tipo</th>
                                    <th>@Resources.Valor</th>
                                    <th>@Resources.ServicioWeb</th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Fitosanidad/Views/IOT_SensorList/Edit.cshtml
@using Resources;
@using Planner.Model;

@model Planner.Model.IOT_SensorList


@{
    ViewBag.Title = Resources.Sensores + " - " + Resources.Editar;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/IOT_SensorList/Edit.js"></script>

<div class="btn-group">
    <button id="btnHome" name="btnHome" class="btn btn-warning waves-effect waves-light" data-toggle="tooltip" data-placement="top" title="@Resources.VolverALaLista" onclick='BackToList()'>
        <i class="fa fa-chevron-left"></i>
    </button>
    <button id="btnSave" name="btnSave" class="btn btn-success waves-effect waves-light" data-toggle="tooltip" data-placement="top" title="@Resources.Grabar" onclick="CallSubmit()">
        <i class="fa fa-save"></i>
    </button>
</div>
<div class="Planner_Separator">
</div>

@Html.Hidden("IOT_SensorListID")

<div class="box box-success">
    <div class="box-body">
        <div class="col-xs-12 col-sm-12 col-md-12">
            @using (Html.BeginForm("Edit", "IOT_SensorList", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form", id = "Edit" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                @Html.HiddenFor(model => model.IOT_SensorListID)

                <div class="col-xs-12 col-sm-4 col-md-4">
                    <label for="businessUnitList">Unidad de Negocio:</label>
                    @Html.DropDownList("ddlBusinessUnit", ViewData["businessUnitList"] as SelectList, new { @class = "form-control" })
                </div>
                <div class="col-xs-12 col-sm-4 col-md-4">
                    <label for="greenhouseList">@Resources.Bloque</label>
                    @Html.DropDownList("ddlGreenhouse", ViewData["greenhouseList"] as SelectList, new { @class = "form-control", onchange = "greenhouseListOnChange()" })
                </div>
                <div class="col-xs-12 col-sm-4 col-md-4">
                    <label for="Description">@Resources.Ubicacion</label>
                    @Html.TextBoxFor(model => model.Name, null, new { @class = "form-control", @placeholder = Resources.Ubicacion})
                </div>

                <div class="col-xs-12 col-sm-4 col-md-4">
                    <label for="lstPlanner_TemplateType">@Resources.ServicioWeb</label>
                    <div class="controls">
                        @Html.TextBoxFor(model => model.Service, null, new { @class = "form-control", @placeholder = Resources.ServicioWeb })
                    </div>
                </div>
                <div class="col-xs-12 col-sm-4 col-md-4">
                    <label for="lstPlanner_TemplateType">@Resources.IdSensor</label>
                    <div class="controls">
                        @Html.TextBoxFor(model => model.ExternalID, null, new { @class = "form-control", @placeholder = Resources.IdSensor })
                    </div>
                </div>

                <div class="col-xs-12 col-sm-1 col-md-1">
                    <label for="ActiveFlag">@Resources.Activo</label>
                    @Html.CheckBoxFor(model => model.FlagActive, new { @class = "checkbox" })
                </div>
            }
        </div>
    </div>
</div>

Fitosanidad/Views/IOT_SensorList/Index.cshtml
@using Resources;

@{
    ViewBag.Title = Resources.Sensores;
}

<script src="~/Scripts/IOT_SensorList/IOT_SensorList.js"></script>

<div class="btn-group">
    <button id="btnCreate" name="btnCreate" class="btn btn-success waves-effect waves-light" data-toggle="tooltip" data-placement="top" title="@Resources.Adicionar" >
        <i class="fa fa-plus"></i>
    </button>
    <button id="dataSensor" name="dataSensor" class="btn btn-success waves-effect waves-light" data-toggle="tooltip" data-placement="top" title="@Resources.ExportarExcel" >
        <i class="fa fa-file-excel-o"></i>
    </button>
</div>
<div class="Planner_Separator">
</div>
<div class="box box-success">
    <div class="box-body">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                @Html.Partial("SensorList")
            </div>
        </div>
    </div>
</div>

Fitosanidad/Views/IOT_SensorList/SensorList.cshtml
@using Resources;

@model Planner.Model.SIEMBRAS_PLANNEREntities

<div id="SensorDataTable" class="form-group row">
    <div id="resultsSensor">
        <table id="tableSensor" class="frozen_alert table table-bordered table-striped table-condensed table-hover">
            <thead>
                <tr>
                    <th>@Resources.Id</th>
                    <th>@Resources.IdSensor</th>
                    <th>@Resources.Ubicacion</th>
                    <th>@Resources.UnidadDeNegocio</th>
                    <th>@Resources.IdInvernadero</th>
                    <th>@Resources.ServicioWeb</th>
                    <th>@Resources.Activo</th>
                    <th>@Resources.Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var sensor in ViewBag.SensorList)
                {
                    <tr>
                        <td>@sensor.IOT_SensorListID</td>
                        <td>@sensor.ExternalID</td>
                        <td>@sensor.Name</td>
                        <td>@sensor.BusinessUnitName</td>
                        <td>@sensor.Codigo</td>
                        <td>@sensor.Service</td>
                        <td>@Html.CheckBox("chkFlagActive", (bool)sensor.FlagActive, new { @disabled = "disabled" })</td>
                        <td class="actions">
                            <div class="btn-group">
                                <button class="btn btn-xs" type="button" data-toggle="tooltip" data-placement="top" title="@Resources.Editar" onclick="location='/IOT_SensorList/Edit?IOT_SensorListID=@sensor.IOT_SensorListID'">
                                    <i class="fa fa-pencil text-blue"></i>
                                </button>
                                <button class="btn btn-xs" type="button" data-toggle="tooltip" data-placement="top" title="@Resources.Borrar" onclick="location='/IOT_SensorList/Delete?IOT_SensorListID=@sensor.IOT_SensorListID'">
                                    <i class="fa fa-trash-o text-danger"></i>
                                </button>
                                <button class="btn btn-xs" type="button" data-toggle="tooltip" data-placement="top" title="@Resources.CargarInformacion" onclick="location='/IOT_SensorList/Upload?IOT_SensorListID=@sensor.IOT_SensorListID'">
                                    <i class="fa fa-upload text-warning"></i>
                                </button>
                                <button class="btn btn-xs" type="button" data-toggle="tooltip" data-placement="top" title="@Resources.BorrarInformacionEnUnRangoDeFechas" onclick="location='/IOT_SensorList/DeleteDateRange?IOT_SensorListID=@sensor.IOT_SensorListID'">
                                    <i class="fa fa-calendar-times-o text-danger"></i>
                                </button>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>